from __future__ import annotations
from typing import Protocol, Optional, List, Any
from datetime import date, datetime

class ProjectRepository(Protocol):
    def get(self, tenant_id: str, project_id: str) -> Any: ...
    def list_by_program(self, tenant_id: str, program_id: str) -> List[Any]: ...
    def list_by_user(self, tenant_id: str, user_id: str) -> List[Any]: ...

class TaskRepository(Protocol):
    def get(self, tenant_id: str, project_id: str, task_id: str) -> Any: ...
    def list_by_project(self, tenant_id: str, project_id: str) -> List[Any]: ...
    def list_by_assignee(self, tenant_id: str, user_id: str) -> List[Any]: ...
    def list_by_status(self, tenant_id: str, project_id: str, status: str) -> List[Any]: ...
    def list_overdue(self, tenant_id: str, project_id: str, as_of_date: date) -> List[Any]: ...
    def create(self, item: Any) -> Any: ...
    def update(self, item: Any, expected_version: int) -> Any: ...
    def conditional_update(self, tenant_id: str, project_id: str, task_id: str, updates: dict, expected_version: int) -> Any: ...

class RiskRepository(Protocol):
    def get(self, tenant_id: str, project_id: str, risk_id: str) -> Any: ...
    def list_by_project(self, tenant_id: str, project_id: str) -> List[Any]: ...
    def list_by_status(self, tenant_id: str, project_id: str, status: str) -> List[Any]: ...
    def list_by_owner(self, tenant_id: str, user_id: str) -> List[Any]: ...
    def create(self, item: Any) -> Any: ...
    def update(self, item: Any, expected_version: int) -> Any: ...

class ReportRepository(Protocol):
    def get(self, tenant_id: str, project_id: str, report_id: str) -> Any: ...
    def list_by_project(self, tenant_id: str, project_id: str) -> List[Any]: ...
    def create(self, item: Any) -> Any: ...

class MembershipRepository(Protocol):
    def get_tenant_membership(self, tenant_id: str, user_id: str) -> Any: ...
    def get_project_member(self, tenant_id: str, project_id: str, user_id: str) -> Any: ...
    def add_project_member(self, member: Any) -> Any: ...
    def remove_project_member(self, tenant_id: str, project_id: str, user_id: str) -> Any: ...

class ConnectorRepository(Protocol):
    def get(self, tenant_id: str, connector_id: str) -> Any: ...
    def list_by_tenant(self, tenant_id: str) -> List[Any]: ...
    def list_by_status(self, tenant_id: str, status: str) -> List[Any]: ...
    def get_config(self, tenant_id: str, connector_id: str) -> Any: ...
    def create(self, item: Any) -> Any: ...
    def update(self, item: Any, expected_version: int) -> Any: ...

class WorkflowRepository(Protocol):
    def get(self, tenant_id: str, workflow_id: str) -> Any: ...
    def list_by_user(self, tenant_id: str, user_id: str) -> List[Any]: ...
    def list_by_project(self, tenant_id: str, project_id: str) -> List[Any]: ...
    def list_by_status(self, tenant_id: str, status: str) -> List[Any]: ...
    def create_with_idempotency(self, workflow: Any, idempotency_record: Any) -> Any: ...
    def update_status(self, workflow_id: str, expected_version: int, new_status: str, allowed_statuses: List[str]) -> Any: ...
    def get_task_attempts(self, workflow_id: str, task_id: str) -> List[Any]: ...

class ApprovalRepository(Protocol):
    def get(self, workflow_id: str, approval_id: str) -> Any: ...
    def list_pending_for_user(self, tenant_id: str, user_id: str) -> List[Any]: ...
    def create(self, item: Any) -> Any: ...
    def decide(self, workflow_id: str, approval_id: str, status: str, decided_by: str, decided_at: datetime) -> Any: ...

class IdempotencyRepository(Protocol):
    def get(self, tenant_id: str, user_id: str, key_hash: str) -> Any: ...
    def create(self, item: Any) -> Any: ...

class ArtifactRepository(Protocol):
    def get(self, tenant_id: str, artifact_id: str) -> Any: ...
    def list_by_workflow(self, workflow_id: str) -> List[Any]: ...
    def create(self, item: Any) -> Any: ...
